Repository DILab-Ivy/ivy-testing-ui, pull requests merged in 2024-07, with the labels that each got.

#2 Refactor dislike/flagged response handling, clean-up and organizing test scripts
  main.py
  test_dynamodb_connection.py
  test_scripts/test_dynamodb_connection.py
Labels: enhancement

#3 Implement Direct File Download with DownloadButton
  main.py
Labels: sprint

#4 Login Functionality & Multiple pages in App & Allow Choosing skills & Developer View
  main.py
  requirements.txt
  test_scripts/test_cognito_connection.py
Labels: sprint

#5 Update ReadMe file
  README.md
Labels: documentation

#7 Add user login logging with Dynamodb
  main.py
Labels: sprint
